### PR TITLE
Cake.Core 0.26.0 support

### LINKED ISSUE #11: Support for Cake v0.26.0
Build against Cake 0.26.0 to support Cake versions >= 0.26.0

### PR DESCRIPTION
**Pull request by nmbro**
Updated Cake.Core 0.26.0

I had to comment out a test that failed to compile.

Fixes #11

### CODE REVIEW

**Comment by wozzo** [comment]
Appreciate the PR, but a lot more has changed here than upgrading the referenced version of Cake. 
The change to use the new csproj will not work with Cake.Recipe since the [ParseProject function doesn't work with the new format](https://github.com/cake-build/cake/issues/1662). This has the effect of not running the unit tests as you can see from the "Skipped" statements on the [AppVeyor build](https://ci.appveyor.com/project/cakecontrib/cake-graph/build/0.5.0-PullRequest.12+3.build.46) 
The Cake.Recipe version is deliberately pinned so that builds that passed one day will still pass at any point later.
I'm not sure why the unit tests needed to be removed/commented out, but they're testing core functionality of the graph project

**Comment by wozzo** [comment]
@nmbro If you change the line gep references above, pin the version of cake.recipe, and if you can get those unit tests working again I'll bring this in, or I'll do it on Monday. Thanks again

**Comment by wozzo** [comment]
Thanks again. Were you not able to get the Manager_Parses_Razor_Template or Can_Read_Embedded_Resource_To_String tests workingagain?

**Comment by nmbro** [comment]
@wozzo Oh I was missing GraphTemplateRepositoryTests.cs file from my tests - don't know why that was.
They are working now

**Comment by wozzo** [comment]
Thanks for the PR @nmbro

**Pull request merged**
